spring:

  application:
    name: ExchangeCampusSecondHandTradingPlatform

  datasource:
    url: jdbc:mysql://exchange-mysql:3306/exchange_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc200519P

  data:
    redis:
      host: exchange-redis
      port: 6379
      password: abc200519P

  mail:
    host: smtp.qq.com
    port: 587
    username: exchange_office@qq.com
    password: nxcinljibzmvcgcc
    default-encoding: UTF-8
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

# 事务日志
logging:
  level:
    org.springframework.transaction: debug


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.exchange.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

exchange_file:
  delete-file-path-prefix: /root/ExchangeApp/
  local-path: /root/ExchangeApp/ExchangeUploads/
  prefix: /ExchangeUploads/